### ISSUE TITLE
Edit existing data

### ISSUE THREAD

**Issue by ToniGlasl** [flomaurer/Tourenverzeichnis#12]
hey, it would be good if you included a way to edit existing data, tracks and images.

**Comment by flomaurer** [comment]
you can - just open a tour and change the values - the existing tour will be updated

**Comment by ToniGlasl** [comment]
maybe it's a problem with me PC but it doesn't work

**Comment by flomaurer** [comment]
I'll figure out.

Maybe you can send me screenshots of your steps (in this issue here)
