### ISSUE TITLE
Database images 

### ISSUE THREAD

**Issue by ToniGlasl** [flomaurer/Tourenverzeichnis#13]
maybe you can organise images in the Database, so then you can give all images a individual ID and the users have no problems with the saving if a tour has the same name.

and the same for the GPX tracks

**Comment by flomaurer** [comment]
there is no problem with the same name, as the tours are saved by their date in combination with the goal of the tour
I don't think you will head the same goal twice a day within different activities

**Comment by ToniGlasl** [comment]
ok but you have a warning which pointed to the risk
