### ISSUE TITLE
Tour types

### ISSUE THREAD

**Issue by ToniGlasl** [flomaurer/Tourenverzeichnis#15]
it would be another great tool, if you can create and edit your Tour types easy in the front end

**Comment by flomaurer** [comment]
you can type in any tour-type you want - but just a few are suggested.

If I got time, I'll think of extending the suggestions

**Comment by flomaurer** [comment]
can be done in combination with issue #9

**Comment by flomaurer** [comment]
solved in runtime - on startup, the GUI serches for Types already present in the DB.
So once added an activity, it will be always suggested
